# Generated by Django 4.2.27 on 2025-12-30 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='topic_1',
            new_name='topic',
        ),
    ]
